# fly.toml file generated for church-management-backend
app = "church-management-backend"
primary_region = "ord"

[build]
  builder = "heroku"

[http_service]
  internal_port = 3000
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[mounts]]
  source = "data"
  destination = "/data"

[env]
  NODE_ENV = "production"

[processes]
  app = "npm start"
